/**
* @File Name : CallPlanCalendar.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : May 9, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 9, 2025 |   | Initial Version
**/

public class CallPlanCalendar {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}