/**
* @File Name : checkAndSendEmail.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : May 22, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 22, 2025 |   | Initial Version
**/

public class checkAndSendEmail {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}